apiVersion: apps/v1
kind: Deployment
metadata:
  name: besant-tech
  labels: 
    app: besant-tech
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: besant-tech
  template: 
    metadata:
      labels:
        app: besant-tech
        tier: frontend
    specs:
      initContainers:
      - name: init-db
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
        - name: besant-tech
          image: <image-name> # Add Your Image here
          ports:
            - containerPort: 80
          env:
              - name: DB_HOSTNAME
                value: "mysql"            
              - name: DB_PORT
                value: "3306"            
              - name: DB_NAME
                value: "database-name"            
              - name: DB_USERNAME
                value: "root"            
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-db-password
                    key: db-password             