apiVersion: apps/v1
kind: Deployment
metadata:
  name: besant-tech
  labels: 
    app: besant-tech
    tier: frontend
spec:
  initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
  replicas: 3
  selector:
    matchLabels:
      app: besant-tech
  template: 
    metadata:
      labels:
        app: besant-tech
        tier: frontend
    specs:
      containers:
        - name: besant-tech
          image: <image-name> # Add Your Image here
          ports:
            - containerPort: 80