apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc # it should be same as you have give name: ebs-sc in StorageClass.yaml file.
  resources: 
    requests:
      storage: 4Gi